/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  bittensorSidebar: [
    // 	{
    // 	type: 'link',
    // 	href: 'https://docs.bittensor.com',
    // 	label: "Search",
    // 	className: 'sidebarSearch', //  based on Class name it will add search component
    // },
    "index",
    "whats-new-in-docs",
    "questions-and-answers",
    {
      type: "category",
      label: "Learn Cybertensor Concepts",
      collapsible: true,
      collapsed: false,
      items: [
        "learn/introduction",
        "learn/bittensor-building-blocks",
        "learn/anatomy-of-incentive-mechanism",
      ],
    },
    {
      type: "category",
      label: "Get Started",
      collapsible: true,
      collapsed: false,
      items: [
        "getting-started/installation",
        "getting-started/wallets",
      ],
    },
    // {
    //   type: "category",
    //   label: "Subtensor Nodes",
    //   link: {type: "doc", id: "subtensor-nodes/index",},
    //   collapsible: true,
    //   collapsed: false,
    //   items: [
    //     "subtensor-nodes/subtensor-node-requirements",
    //     "subtensor-nodes/using-source",
    //     "subtensor-nodes/using-docker",
    //   ],
    // },
    {
      type: "category",
      label: "Validating and Mining",
      collapsible: true,
      collapsed: false,
      items: [
        "subnets/checklist-for-validating-mining",
        "subnets/register-validate-mine",
        "subnets/working-with-keys",
      ],
    },
    {
      type: "category",
      label: "Staking and Delegation",
      collapsible: true,
      collapsed: false,
      link: {type: "doc", id: "staking-and-delegation/index",},
      items: ["staking-and-delegation/staking-polkadot-js", "staking-and-delegation/delegation",],
    },
    {
      type: "category",
      label: "Subnet Tutorials",
      collapsible: true,
      collapsed: false,
      items: [
        "tutorials/basic-subnet-tutorials",
        "tutorials/ocr-subnet-tutorial",
      ],
    },
    {
      type: "category",
      label: "Subnets",
      collapsible: true,
      collapsed: false,
      items: [
        "subnets/create-a-subnet", 
        "subnets/subnet-hyperparameters",
        "subnets/working-with-subnets",
        "subnets/walkthrough-prompting",
      ],
    },
    {
      type: "category",
      label: "Subnet Pages",
      link: {type: "doc", id: "subnet-pages/index",},
      collapsible: true,
      collapsed: true,
      items: [
        "subnet-pages/subnet-0",
        "subnet-pages/subnet-1",
      ],
    },
    "ctcli",
    "ct-api-ref",
    "emissions",
    "root-network",
    // "reference/cybertensor-api-ref",
    "yuma-consensus",
    "governance",
    "senate",
    "utilities",
    "glossary",
  ],
};

module.exports = sidebars;
